version: "3"
services:
  mongodb:
    image: mongo:3.6.12
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    image: accountbook/accountbook
    ports:
    - 8080:8080
    links:
    - mongodb